# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mamamiyear's blog
baseurl: "" # the sub path of your site, e.g. /blog
url: "http://blog.mamamiyear.me" # the base hostname & protocol for your site

# Social settings
email: mamamiyear@163.com
weibo:   mamamiyearwar3sc2
github:  mamamiyear

# Blogger settings
description:  有些弯路是一定要走的，有些挫折是必须承受的

# Build settings
markdown: kramdown

# Copyright
copyright: Copyright ©2017 mamamiyear.me
license: The MIT License

# Jekyll service settings
#host: 0.0.0.0
#port: 8080
